#!/usr/bin/env python3
"""把 NSwag 单文件输出按类拆成多文件。

输入：NSwag 生成的 src/Controllers/Generated/Controllers.cs（含 11 ControllerBase + N DTO）
输出：
  - src/Controllers/Generated/<Tag>ControllerBase.cs（11 文件）
  - src/Models/Generated/<Dto>.cs（N 文件）

策略：
  - 用 brace-matching 切分顶层 `public class Xxx` 块（包括前面的 [GeneratedCode] attribute）
  - ControllerBase 类 → Controllers/Generated/<Tag>ControllerBase.cs（Xxx → Xxx, 保留 ControllerBase 后缀）
  - 其他 partial class（DTO） → Models/Generated/<Dto>.cs（去掉可能的后缀，统一文件名）

为什么不直接用 Roslyn：
  NSwag 输出格式固定（每类一个 GeneratedCode attribute + 4 空格缩进 + 单层类定义，无嵌套类），
  brace-matching + regex 足够可靠；引入 Roslyn 增加构建依赖和 binary 体积（200KB → 50MB+）。
  若未来 NSwag 输出格式变化（嵌套类、record struct 等），改用 tree-sitter-c-sharp 升级。

用法：python3 scripts/split-nswag-output.py <src-file> <out-controllers-dir> <out-models-dir>
"""
from __future__ import annotations
import re
import sys
from pathlib import Path


# 匹配每个顶层 type 声明的起始（含前面的 [GeneratedCode] attribute 行，可选）。
# NSwag 固定 4 空格缩进。涵盖 class（含 abstract/partial）+ enum（lab 含 4 个 enum，
# 无前置 attribute）。
TYPE_HEADER_RE = re.compile(
    r'^(?P<indent>    )(?P<attrs>(?:\s*\[[^\]]*\]?\s*\n)*?)    (?P<kind>public (?:abstract |partial )?class|public enum) (?P<name>\w+)',
    re.MULTILINE,
)


def _find_matching_brace(text: str, open_idx: int) -> int:
    """返回与 text[open_idx]='{' 配对的 '}' 索引。"""
    depth = 0
    in_string = False
    in_char = False
    in_verbatim = False
    in_line_comment = False
    in_block_comment = False
    i = open_idx
    while i < len(text):
        c = text[i]
        if in_line_comment:
            if c == '\n':
                in_line_comment = False
        elif in_block_comment:
            if c == '*' and i + 1 < len(text) and text[i + 1] == '/':
                in_block_comment = False
                i += 1
        elif in_string:
            if c == '\\':
                i += 1
            elif c == '"':
                in_string = False
        elif in_char:
            if c == '\\':
                i += 1
            elif c == "'":
                in_char = False
        elif in_verbatim:
            if c == '"':
                in_verbatim = False
        else:
            if c == '/' and i + 1 < len(text):
                nxt = text[i + 1]
                if nxt == '/':
                    in_line_comment = True
                    i += 1
                elif nxt == '*':
                    in_block_comment = True
                    i += 1
            elif c == '"':
                # 检查是否为 verbatim string (@"...")
                if i > 0 and text[i - 1] == '@':
                    in_verbatim = True
                else:
                    in_string = True
            elif c == "'":
                in_char = True
            elif c == '{':
                depth += 1
            elif c == '}':
                depth -= 1
                if depth == 0:
                    return i
        i += 1
    raise ValueError(f"未找到匹配的 '}}'（open_idx={open_idx}）")


def _file_header(usings_block: str, namespace: str, pragma_block: str) -> str:
    # lab-aspnetcore 的 FromQuery string? 注解需要 `#nullable enable` 上下文（CS8669）
    # 在每个 per-class 文件头注入；saas-aspnetcore 不需要但注入也无害（NSwag 已含 ? 但
    # 仅在 string FromQuery 上）。patch-generated.py 也会注入 `#nullable enable` 在
    # AllGenerated.cs；split 后落到每个 per-class 文件可能产生重复 `#nullable enable` —
    # C# 编译器允许多次 `#nullable enable`（幂等），但为干净起见，去重：
    nullable_directive = "#nullable enable\n"
    # CS8618 disable 已通过 deduped_pragmas 处理（保留 patch-generated.py 注入的一行）

    # 去重 pragma block 中的 CS8618 行（patch-generated.py 已注入，避免双重 disable）
    pragma_lines = pragma_block.splitlines()
    seen_cq: set[str] = set()
    deduped_pragmas: list[str] = []
    for line in pragma_lines:
        if "CS8618" in line:
            if "CS8618" in seen_cq:
                continue
            seen_cq.add("CS8618")
        deduped_pragmas.append(line)
    pragma_block_clean = "\n".join(deduped_pragmas)

    return (
        "//----------------------\n"
        "// <auto-generated>\n"
        "//     Generated using the NSwag toolchain v14.7.1.0 (http://NSwag.org)\n"
        "//     Post-split by scripts/split-nswag-output.py\n"
        "// </auto-generated>\n"
        "//----------------------\n\n"
        f"{usings_block}\n"
        f"{pragma_block_clean}\n"
        f"{nullable_directive}\n"
        f"namespace {namespace}\n"
        "{\n"
        "    using System = global::System;\n\n"
    )


def split_file(src_path: Path, controllers_dir: Path, models_dir: Path) -> int:
    text = src_path.read_text(encoding="utf-8")
    # 抽取头部：using + pragma + namespace 起始行
    # 找 namespace {...} 块
    ns_match = re.search(r"^namespace\s+(\S+)\s*\n\{", text, re.MULTILINE)
    if not ns_match:
        raise ValueError(f"未找到 namespace 声明：{src_path}")
    namespace = ns_match.group(1)
    ns_open = ns_match.end() - 1  # '{' 索引

    # usings + pragma block：取 namespace 之前的内容
    head = text[: ns_match.start()]
    using_lines: list[str] = []
    pragma_lines: list[str] = []
    for line in head.splitlines():
        if line.startswith("using ") or line.startswith("using\t"):
            using_lines.append(line)
        elif line.startswith("#pragma "):
            pragma_lines.append(line)
    usings_block = "\n".join(using_lines)
    pragma_block = "\n".join(pragma_lines)

    # 在 namespace 内收集所有顶层 type 块
    # 起始：从 ns_open+1（即 '{' 后），结束：找到匹配的 '}'
    ns_close = _find_matching_brace(text, ns_open)
    body = text[ns_open + 1 : ns_close]

    # 找所有类型声明头（属性块 + kind + name）
    matches: list[tuple[int, str, str]] = []
    for m in TYPE_HEADER_RE.finditer(body):
        attrs = m.group("attrs")
        kind = m.group("kind")
        name = m.group("name")
        matches.append((m.start(), attrs, name, kind))

    # 切分：每个匹配块 = 从 m.start() 到下一个匹配 start 之前；最后一个到 body 末尾
    chunks: list[tuple[str, str]] = []
    for i, (start, attrs, name, _kind) in enumerate(matches):
        end = matches[i + 1][0] if i + 1 < len(matches) else len(body)
        # 块内第一个 '{' 是类的 '{'（'public class X { ... }'）
        chunk_text = body[start:end].rstrip() + "\n"
        chunks.append((name, chunk_text))

    # 写文件
    controllers_dir.mkdir(parents=True, exist_ok=True)
    models_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    for name, chunk in chunks:
        if name.endswith("ControllerBase"):
            # Controller：文件名用 <Tag>ControllerBase.cs（去掉 'Base' 后缀更清晰）
            tag = name[: -len("Base")]  # AdminClientsController
            target = controllers_dir / f"{tag}.cs"
        else:
            # DTO：原名
            target = models_dir / f"{name}.cs"
        # 构造最终文件内容（带 namespace 包裹）
        file_content = _file_header(usings_block, namespace, pragma_block)
        file_content += chunk
        file_content += "}\n"  # 闭合 namespace
        target.write_text(file_content, encoding="utf-8")
        try:
            written.append(str(target.relative_to(src_path.parent)))
        except ValueError:
            written.append(str(target))

    return len(written)


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "usage: split-nswag-output.py <src-file> <out-controllers-dir> <out-models-dir>",
            file=sys.stderr,
        )
        return 2
    src = Path(sys.argv[1])
    cdir = Path(sys.argv[2])
    mdir = Path(sys.argv[3])
    if not src.exists():
        print(f"源文件不存在：{src}", file=sys.stderr)
        return 2
    n = split_file(src, cdir, mdir)
    print(f"[split] 拆出 {n} 个类 → {cdir} ({sum(1 for f in cdir.glob('*.cs'))} controllers) + {mdir} ({sum(1 for f in mdir.glob('*.cs'))} models)")
    return 0


if __name__ == "__main__":
    sys.exit(main())